--- #YAML:1.0
name:                XML-CAP
version:             0.01
abstract:            parse or generate the XML Common Alerting Protocol (CAP)
license:             perl
author:              
    - Ian Kluft <ikluft@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
